# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spotify_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Spotify(object):
    def setupUi(self, Spotify):
        Spotify.setObjectName("Spotify")
        Spotify.resize(1253, 857)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        Spotify.setFont(font)
        Spotify.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Spotify.setWindowIcon(icon)
        Spotify.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Spotify)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(-40, -60, 1291, 921))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setItalic(True)
        self.frame.setFont(font)
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.group_box = QtWidgets.QGroupBox(self.frame)
        self.group_box.setGeometry(QtCore.QRect(60, 490, 151, 271))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.group_box.setFont(font)
        self.group_box.setObjectName("group_box")
        self.playlists = QtWidgets.QListWidget(self.group_box)
        self.playlists.setGeometry(QtCore.QRect(0, 40, 151, 211))
        self.playlists.setStyleSheet("color: rgb(255, 255, 255);")
        self.playlists.setObjectName("playlists")
        self.activaty = QtWidgets.QGroupBox(self.frame)
        self.activaty.setGeometry(QtCore.QRect(60, 190, 151, 241))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.activaty.setFont(font)
        self.activaty.setObjectName("activaty")
        self.Test = QtWidgets.QPushButton(self.activaty)
        self.Test.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.Test.setObjectName("Test")
        self.logoplaylist = QtWidgets.QGraphicsView(self.frame)
        self.logoplaylist.setGeometry(QtCore.QRect(230, 90, 256, 192))
        self.logoplaylist.setStyleSheet("border-image: url(:/background/background.jpg);")
        self.logoplaylist.setObjectName("logoplaylist")
        self.PLAYLIST = QtWidgets.QLabel(self.frame)
        self.PLAYLIST.setGeometry(QtCore.QRect(510, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.PLAYLIST.setFont(font)
        self.PLAYLIST.setObjectName("PLAYLIST")
        self.nameofplaylist = QtWidgets.QLabel(self.frame)
        self.nameofplaylist.setGeometry(QtCore.QRect(510, 150, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(18)
        font.setItalic(True)
        self.nameofplaylist.setFont(font)
        self.nameofplaylist.setStyleSheet("color: rgb(255, 255, 255);")
        self.nameofplaylist.setObjectName("nameofplaylist")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(510, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.Nameofauther = QtWidgets.QLabel(self.frame)
        self.Nameofauther.setGeometry(QtCore.QRect(610, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Nameofauther.setFont(font)
        self.Nameofauther.setStyleSheet("color: rgb(255, 255, 255);")
        self.Nameofauther.setObjectName("Nameofauther")
        self.numberofsongs = QtWidgets.QLabel(self.frame)
        self.numberofsongs.setGeometry(QtCore.QRect(770, 250, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberofsongs.setFont(font)
        self.numberofsongs.setStyleSheet("color: rgb(255, 255, 255);")
        self.numberofsongs.setObjectName("numberofsongs")
        self.playplaylist = QtWidgets.QPushButton(self.frame)
        self.playplaylist.setGeometry(QtCore.QRect(1050, 240, 101, 41))
        self.playplaylist.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"selection-background-color: rgb(255, 85, 0);")
        self.playplaylist.setObjectName("playplaylist")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 530, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.refresher = QtWidgets.QPushButton(self.frame)
        self.refresher.setGeometry(QtCore.QRect(1090, 520, 51, 41))
        self.refresher.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.refresher.setMouseTracking(True)
        self.refresher.setAutoFillBackground(False)
        self.refresher.setStyleSheet("border-image: url(:/icon/refresh.png);\n"
"selection-color: rgb(0, 255, 0);")
        self.refresher.setText("")
        self.refresher.setObjectName("refresher")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 780, 1201, 121))
        self.frame_2.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.image_songs = QtWidgets.QGraphicsView(self.frame_2)
        self.image_songs.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.image_songs.setObjectName("image_songs")
        self.Songname = QtWidgets.QLabel(self.frame_2)
        self.Songname.setGeometry(QtCore.QRect(120, 20, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Songname.setFont(font)
        self.Songname.setStyleSheet("color: rgb(255, 255, 255);")
        self.Songname.setObjectName("Songname")
        self.songauther = QtWidgets.QLabel(self.frame_2)
        self.songauther.setGeometry(QtCore.QRect(120, 75, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.songauther.setFont(font)
        self.songauther.setStyleSheet("color: rgb(255, 255, 255);")
        self.songauther.setObjectName("songauther")
        self.playsong = QtWidgets.QPushButton(self.frame_2)
        self.playsong.setGeometry(QtCore.QRect(540, 10, 51, 41))
        self.playsong.setStyleSheet("border-image: url(:/icon/play.ico);")
        self.playsong.setText("")
        self.playsong.setObjectName("playsong")
        self.nextsong = QtWidgets.QPushButton(self.frame_2)
        self.nextsong.setGeometry(QtCore.QRect(630, 10, 51, 41))
        self.nextsong.setStyleSheet("border-image: url(:/icon/next.ico);")
        self.nextsong.setText("")
        self.nextsong.setObjectName("nextsong")
        self.progressofsong = QtWidgets.QSlider(self.frame_2)
        self.progressofsong.setGeometry(QtCore.QRect(430, 80, 671, 22))
        self.progressofsong.setOrientation(QtCore.Qt.Horizontal)
        self.progressofsong.setObjectName("progressofsong")
        self.previous_song = QtWidgets.QPushButton(self.frame_2)
        self.previous_song.setGeometry(QtCore.QRect(450, 10, 51, 41))
        self.previous_song.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previous_song.setStyleSheet("border-image: url(:/icon/previous.png);")
        self.previous_song.setText("")
        self.previous_song.setObjectName("previous_song")
        self.fulltimeofsong = QtWidgets.QLabel(self.frame_2)
        self.fulltimeofsong.setGeometry(QtCore.QRect(1130, 80, 55, 16))
        self.fulltimeofsong.setStyleSheet("color: rgb(255, 255, 255);")
        self.fulltimeofsong.setObjectName("fulltimeofsong")
        self.progressinsong = QtWidgets.QLabel(self.frame_2)
        self.progressinsong.setGeometry(QtCore.QRect(380, 80, 55, 16))
        self.progressinsong.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressinsong.setObjectName("progressinsong")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(940, 20, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.volume = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.volume.setStyleSheet("border-image: url(:/icon/volumeon.ico);")
        self.volume.setText("")
        self.volume.setObjectName("volume")
        self.horizontalLayout.addWidget(self.volume)
        self.volumevalue = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.volumevalue.setOrientation(QtCore.Qt.Horizontal)
        self.volumevalue.setObjectName("volumevalue")
        self.horizontalLayout.addWidget(self.volumevalue)
        self.thumbdown = QtWidgets.QPushButton(self.frame_2)
        self.thumbdown.setGeometry(QtCore.QRect(840, 20, 31, 31))
        self.thumbdown.setStyleSheet("border-image: url(:/icon/thumbdown.ico);")
        self.thumbdown.setText("")
        self.thumbdown.setObjectName("thumbdown")
        self.thumbup = QtWidgets.QPushButton(self.frame_2)
        self.thumbup.setGeometry(QtCore.QRect(780, 20, 31, 31))
        self.thumbup.setStyleSheet("border-image: url(:/icon/thumbup.ico);")
        self.thumbup.setText("")
        self.thumbup.setObjectName("thumbup")
        self.volume_pertg = QtWidgets.QLabel(self.frame_2)
        self.volume_pertg.setGeometry(QtCore.QRect(1150, 20, 21, 29))
        self.volume_pertg.setStyleSheet("color: rgb(255, 255, 255);")
        self.volume_pertg.setObjectName("volume_pertg")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(1170, 20, 21, 29))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(800, 260, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.playlists_details = QtWidgets.QTableWidget(self.frame)
        self.playlists_details.setGeometry(QtCore.QRect(230, 290, 931, 221))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.playlists_details.setFont(font)
        self.playlists_details.setAutoFillBackground(True)
        self.playlists_details.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"font: 8pt \"Segoe UI\";")
        self.playlists_details.setShowGrid(False)
        self.playlists_details.setObjectName("playlists_details")
        self.playlists_details.setColumnCount(0)
        self.playlists_details.setRowCount(0)
        self.Recommender = QtWidgets.QTableWidget(self.frame)
        self.Recommender.setGeometry(QtCore.QRect(230, 560, 931, 201))
        self.Recommender.setObjectName("Recommender")
        self.Recommender.setColumnCount(0)
        self.Recommender.setRowCount(0)
        self.devices = QtWidgets.QToolButton(self.frame)
        self.devices.setGeometry(QtCore.QRect(1050, 90, 91, 41))
        self.devices.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.devices.setObjectName("devices")
        Spotify.setCentralWidget(self.centralwidget)
        self.actionKaishi = QtWidgets.QAction(Spotify)
        self.actionKaishi.setObjectName("actionKaishi")
        self.actionJieshu = QtWidgets.QAction(Spotify)
        self.actionJieshu.setObjectName("actionJieshu")

        self.retranslateUi(Spotify)
        QtCore.QMetaObject.connectSlotsByName(Spotify)

    def retranslateUi(self, Spotify):
        _translate = QtCore.QCoreApplication.translate
        Spotify.setWindowTitle(_translate("Spotify", "Spotify"))
        self.group_box.setTitle(_translate("Spotify", "PLAYLISTS"))
        self.activaty.setTitle(_translate("Spotify", "Your Activaty"))
        self.Test.setText(_translate("Spotify", "Test"))
        self.PLAYLIST.setText(_translate("Spotify", "PLAYLIST"))
        self.nameofplaylist.setText(_translate("Spotify", "NAME"))
        self.label.setText(_translate("Spotify", "Create by:"))
        self.Nameofauther.setText(_translate("Spotify", "Name of artist"))
        self.numberofsongs.setText(_translate("Spotify", "000"))
        self.playplaylist.setText(_translate("Spotify", "Play"))
        self.label_2.setText(_translate("Spotify", "Recommended Songs"))
        self.Songname.setText(_translate("Spotify", "Song name"))
        self.songauther.setText(_translate("Spotify", "Artist of song"))
        self.fulltimeofsong.setText(_translate("Spotify", "5:00"))
        self.progressinsong.setText(_translate("Spotify", "00:00"))
        self.volume_pertg.setText(_translate("Spotify", "00"))
        self.label_4.setText(_translate("Spotify", "%"))
        self.label_5.setText(_translate("Spotify", ": Songs"))
        self.devices.setText(_translate("Spotify", "Devices"))
        self.devices.setShortcut(_translate("Spotify", "F5"))
        self.actionKaishi.setText(_translate("Spotify", "kaishi"))
        self.actionJieshu.setText(_translate("Spotify", "jieshu"))
import res_rc
